sudo: false
language: php

php:
  - '7.0'

install:
  - composer install
  - nvm install && nvm use
  - yarn install

before_script:
  - yarn global add gulp-cli@2.0.1

script:
  - composer run-script phpcs
  - gulp lint-scripts --strict
  - gulp lint-css --strict
  - yarn run build --production
